Equality Check Bug Fix
AY2324S2-CS2103T-W11-1/tp pull request #257
Opened 2024-04-08 15:02 UTC by HM33-Stu

Equality check bug fix
Setting all compulsory fields except application status to be our identity fields

2024-04-11 08:20 UTC, LWS49 commented
additional: add in FAQ the criteria for comparing internships, and that it will be rejected if you key in the same internship

2024-04-11 10:16 UTC, LWS49 requested changes

2024-04-11 10:16 UTC, LWS49 commented on src/test/java/seedu/address/model/internship/InternshipTest.java
>          // different description, all other attributes same -> returns false
Please add checks for new identity fields!
// different role, all other attributes same -> returns false
        editedAlice = new InternshipBuilder(ALICE_MICROSOFT).withRole("Data Analyst").build();
        assertFalse(ALICE_MICROSOFT.isSameInternship(editedAlice));
        
        // different location, all other attributes same -> returns false
        editedAlice = new InternshipBuilder(ALICE_MICROSOFT).withLocation("overseas").build();
        assertFalse(ALICE_MICROSOFT.isSameInternship(editedAlice));

2024-04-11 21:40 UTC, HM33-Stu commented on src/test/java/seedu/address/model/internship/InternshipTest.java
> +
@LWS49 Location and Role test cases added for isSameInternship()

2024-04-11 21:40 UTC, HM33-Stu commented on src/test/java/seedu/address/model/internship/InternshipTest.java
> +        assertFalse(ALICE_MICROSOFT.isSameInternship(editedAlice));
Added in test cases for the remaining identity fields as well

2024-04-13 03:32 UTC, HM33-Stu commented
**Testing For Equality**
I will use the test case by the tester for all variants

**Current State**
isSame -> Company Name, POC, desc, role, location
equals -> Company Name, POC, desc, role, location

![image](https://github.com/AY2324S2-CS2103T-W11-1/tp/assets/120201372/e12d4a8a-fe34-4329-89c0-5e1388e0033a)


**If I add back application status to isSame**
![image](https://github.com/AY2324S2-CS2103T-W11-1/tp/assets/120201372/23d02019-e8d2-456f-9cee-a1de0881e6c5)

2024-04-14 15:09 UTC, CaptainKeqing approved these changes
lgtm

2024-04-14 15:09 UTC, merged