Refactor AddressBook as InternshipData
AY2324S2-CS2103T-W11-1/tp pull request #89
Opened 2024-03-12 15:12 UTC by theman-oj10

Fixes #78, #25 
Implements the updated internship classes to work with the model package. Also updates the Sample Data to work with the new fields.

2024-03-12 19:48 UTC, CaptainKeqing reviewed
LGTM, just a few small nits

For future PR reference:
In general it took awhile to read through the whole change list because creating a new file and changing the fields from the old implementation does not highlight the diffs, so the reviewer has to look through the entire code instead of just the differences.

Also I think it will mess up the code line contribution tracker in the future but I guess it doesnt matter right now

2024-03-12 19:48 UTC, CaptainKeqing commented on src/main/java/seedu/address/model/internship/exceptions/InternshipNotFoundException.java
> + * Signals that the operation is unable to find the specified person.
Should this be internship not person

2024-03-12 19:48 UTC, CaptainKeqing commented on src/main/java/seedu/address/model/internship/Location.java
> +    private enum LocationEnum {
should enums be public

2024-03-12 19:48 UTC, CaptainKeqing commented on src/main/java/seedu/address/model/internship/ApplicationStatus.java
> +    private enum StatusEnum {
should this enum be public too

2024-03-13 04:08 UTC, theman-oj10 commented on src/main/java/seedu/address/model/internship/exceptions/InternshipNotFoundException.java
> + * Signals that the operation is unable to find the specified person.
Yes it has been fixed.

2024-03-13 04:09 UTC, theman-oj10 commented on src/main/java/seedu/address/model/internship/Location.java
> +    private enum LocationEnum {
Yes it has been fixed

2024-03-13 04:09 UTC, theman-oj10 commented on src/main/java/seedu/address/model/internship/ApplicationStatus.java
> +    private enum StatusEnum {
Yes it has been fixed.

2024-03-13 04:27 UTC, CaptainKeqing requested changes

2024-03-13 04:27 UTC, CaptainKeqing commented on src/main/java/seedu/address/model/internship/ApplicationStatus.java
> +    private final StatusEnum applicationStatus;
if private, then we need a getter for this

2024-03-13 04:27 UTC, CaptainKeqing commented on src/main/java/seedu/address/model/internship/Location.java
> +    private final LocationEnum location;
same comment as ApplicationStatus, we need a getter or public final

2024-03-13 04:34 UTC, CaptainKeqing approved these changes
LGTM, thanks for updating

2024-03-13 04:34 UTC, merged